# Generated by Django 4.2.21 on 2025-05-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="googledocument",
            name="embeddings",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googledocument",
            name="processing_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="googledocument",
            name="structured_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingstatus",
            name="current_stage",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
