# Generated by Django 4.2.21 on 2025-05-26 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_googledocument_embeddings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=500)),
                ("role", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=200)),
                ("topic_description_pair", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_status",
                    models.CharField(default="pending", max_length=50),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="course.googledocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_number", models.IntegerField()),
                ("lesson_title", models.CharField(max_length=500)),
                ("lesson_introduction", models.TextField()),
                ("skill_aims", models.TextField()),
                ("language_learning_aims", models.TextField()),
                ("lesson_summary", models.TextField()),
                ("is_bonus", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="course.generatedcourse",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "lesson_number"],
            },
        ),
        migrations.CreateModel(
            name="CourseGenerationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="idle", max_length=50)),
                ("current_step", models.CharField(blank=True, max_length=100)),
                ("orchestrator_output", models.TextField(blank=True)),
                ("worker_outputs", models.TextField(blank=True)),
                ("evaluator_feedback", models.TextField(blank=True)),
                ("final_output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.googledocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
