# Generated by Django 4.2.21 on 2025-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_generatedcourse_generatedlesson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedcourse",
            name="course_description",
            field=models.TextField(default=""),
        ),
    ]
